name: app_router_test
version: 0.1.0+2
author: pjv <ezelspinguin@gmail.com>
description: Tests, demo and documentation for app-router. Original author is Erik Ringsmuth <erik.ringsmuth@gmail.com>.
homepage: https://github.com/pjjjv/app-router-dart-test
dependencies:
  browser: ">=0.10.0+2 <0.11.0"
  core_elements: ">=0.6.0+1 <0.7.0"
  polymer: ">=0.15.3+2 <0.16.0"
  app_router: ">=0.1.0 <0.2.0"
#  app_router:
#    path: ../app_router_dart
  pushstate_anchor: ">=0.1.0 <0.2.0"
#    path: ../pushstate_anchor_dart
dev_dependencies:
  unittest: any
transformers:
- polymer:
    entry_points:
    - web/demo.html
    - test/RouteUri-test.html